server:
  port: 8188
  servlet:
    context-path: /web-market-auth
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/products_b
    postgres:
      console:
        enable: true
        settings:
          web-allow-others: false

jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g
  lifetime: 36000000