server:
  port: 8188
  servlet:
    context-path: /market-auth
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/products_b
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g
  lifetime: 36000000