server:
  port: 8189
  servlet:
    context-path: /app
utils:
  cart:
    prefix: SPRING_WEB_
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/products_b
    postgres:
      console:
        enable: true
        settings:
          web-allow-others: false