server:
  port: 8189
  servlet:
    context-path: /market-core
utils:
  cart:
    prefix: SPRING_WEB_
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/products
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
integrations:
  cart-service:
    url: http://localhost:5555/cart
jwt:
 secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g
 lifetime: 36000000